2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_setup.py:_flush():68] Current SDK version is 0.19.4
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_setup.py:_flush():68] Configure stats pid to 70447
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_setup.py:_flush():68] Loading settings from /Users/aman/.config/wandb/settings
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_setup.py:_flush():68] Loading settings from /Users/aman/Documents/Work/Machine Learning/Computer-Vision-TensorFlow/Weights&Biases-Integration/wandb/settings
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_init.py:setup_run_log_directory():624] Logging user logs to /Users/aman/Documents/Work/Machine Learning/Computer-Vision-TensorFlow/Weights&Biases-Integration/wandb/run-20250127_124212-n55fuqzw/logs/debug.log
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_init.py:setup_run_log_directory():625] Logging internal logs to /Users/aman/Documents/Work/Machine Learning/Computer-Vision-TensorFlow/Weights&Biases-Integration/wandb/run-20250127_124212-n55fuqzw/logs/debug-internal.log
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_init.py:monkeypatch_ipython():576] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x35f64cc10>
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_init.py:init():743] calling init triggers
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_init.py:init():748] wandb.init called with sweep_config: {'DROPOUT_RATE': 0.2647709010473697, 'LEARNING_RATE': 0.0777055846847652, 'N_DENSE_1': 128, 'N_DENSE_2': 32, 'REGULARIZATION_RATE': 0.02484577717720783}
config: {'LEARNING_RATE': 0.001, 'N_EPOCHS': 10, 'BATCH_SIZE': 128, 'DROPOUT_RATE': 0.0, 'IM_SIZE': 224, 'REGULARIZATION_RATE': 0.0, 'N_FILTERS': 6, 'KERNEL_SIZE': 3, 'N_STRIDES': 1, 'POOL_SIZE': 2, 'N_DENSE_1': 128, 'N_DENSE_2': 32}
2025-01-27 12:42:12,549 INFO    Thread-8 (_run_job):70447 [wandb_init.py:init():776] starting backend
2025-01-27 12:42:12,784 INFO    Thread-8 (_run_job):70447 [wandb_init.py:init():780] sending inform_init request
2025-01-27 12:42:12,788 INFO    Thread-8 (_run_job):70447 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-01-27 12:42:12,788 INFO    Thread-8 (_run_job):70447 [wandb_init.py:init():795] backend started and connected
2025-01-27 12:42:12,793 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_config_callback():1270] config_cb None None {'DROPOUT_RATE': 0.2647709010473697, 'LEARNING_RATE': 0.0777055846847652, 'N_DENSE_1': 128, 'N_DENSE_2': 32, 'REGULARIZATION_RATE': 0.02484577717720783}
2025-01-27 12:42:12,799 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_label_probe_notebook():1213] probe notebook
2025-01-27 12:42:12,799 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_label_probe_notebook():1223] Unable to probe notebook: Expecting value: line 1 column 1 (char 0)
2025-01-27 12:42:12,800 INFO    Thread-8 (_run_job):70447 [wandb_init.py:init():888] updated telemetry
2025-01-27 12:42:12,840 INFO    Thread-8 (_run_job):70447 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-01-27 12:42:13,138 INFO    Thread-8 (_run_job):70447 [wandb_init.py:init():967] starting run threads in backend
2025-01-27 12:42:13,277 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_console_start():2409] atexit reg
2025-01-27 12:42:13,277 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_redirect():2259] redirect: wrap_raw
2025-01-27 12:42:13,277 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_redirect():2324] Wrapping output streams.
2025-01-27 12:42:13,277 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_redirect():2349] Redirects installed.
2025-01-27 12:42:13,277 INFO    Thread-8 (_run_job):70447 [wandb_init.py:init():1009] run started, returning control to user process
2025-01-27 12:42:18,247 INFO    MainThread:70447 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-01-27 12:42:18,248 INFO    MainThread:70447 [wandb_init.py:_pause_backend():541] pausing backend
2025-01-27 12:42:22,425 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_finish():2134] finishing run amanjn2003-santa-clara-university/uncategorized/n55fuqzw
2025-01-27 12:42:22,425 INFO    Thread-8 (_run_job):70447 [jupyter.py:save_history():458] not saving jupyter history
2025-01-27 12:42:22,425 INFO    Thread-8 (_run_job):70447 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-01-27 12:42:22,425 INFO    Thread-8 (_run_job):70447 [wandb_init.py:_jupyter_teardown():558] cleaning up jupyter logic
2025-01-27 12:42:22,425 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_atexit_cleanup():2374] got exitcode: 1
2025-01-27 12:42:22,426 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_restore():2356] restore
2025-01-27 12:42:22,426 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_restore():2362] restore done
2025-01-27 12:42:22,426 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_restore():2356] restore
2025-01-27 12:42:22,426 INFO    Thread-8 (_run_job):70447 [wandb_run.py:_restore():2362] restore done
2025-01-27 12:42:22,426 ERROR   Thread-8 (_run_job):70447 [wandb_run.py:_atexit_cleanup():2395] Problem finishing run
Traceback (most recent call last):
  File "/var/folders/8v/j561wc497p1672n3xvshbbd00000gn/T/ipykernel_70447/140730578.py", line 10, in train
    model.fit(trainDataset, validation_data=valDataset, epochs=config.N_EPOCHS, callbacks=[WandbMetricsLogger(), WandbModelCheckpoint("Models/TunedModel.keras")])
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/wandb/sdk/lib/redirect.py", line 645, in write
    self._old_write(data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/iostream.py", line 694, in write
    self._schedule_flush()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/iostream.py", line 590, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/zmq/sugar/socket.py", line 701, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_zmq.py", line 1092, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1134, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1209, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/var/folders/8v/j561wc497p1672n3xvshbbd00000gn/T/ipykernel_70447/140730578.py", line 2, in train
    with wandb.init(name="Run 3 - Hyperparamter Tuning", project="Malaria-Detection", entity="amanjn2003-santa-clara-university", config=CONFIGURATION) as run:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 3636, in __exit__
    traceback.print_exception(exc_type, exc_val, exc_tb)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/traceback.py", line 125, in print_exception
    te.print(file=file, chain=chain)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/traceback.py", line 1022, in print
    print(line, file=file, end="")
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/wandb/sdk/lib/redirect.py", line 645, in write
    self._old_write(data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/iostream.py", line 694, in write
    self._schedule_flush()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/iostream.py", line 590, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/zmq/sugar/socket.py", line 701, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_zmq.py", line 1092, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1134, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1209, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2386, in _atexit_cleanup
    self._on_finish()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2633, in _on_finish
    with progress.progress_printer(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/wandb/sdk/lib/progress.py", line 40, in progress_printer
    with printer.dynamic_text() as text_area:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/wandb/sdk/lib/printer.py", line 436, in dynamic_text
    handle = self._ipython_display.display(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/IPython/core/display_functions.py", line 305, in display
    publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/IPython/core/display_functions.py", line 93, in publish_display_data
    display_pub.publish(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 103, in publish
    self._flush_streams()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 66, in _flush_streams
    sys.stdout.flush()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/iostream.py", line 604, in flush
    self.pub_thread.schedule(self._flush)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/site-packages/zmq/sugar/socket.py", line 701, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_zmq.py", line 1092, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1134, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1209, in zmq.backend.cython._zmq._check_closed
zmq.error.ZMQError: Socket operation on non-socket
